### ISSUE TITLE
SUBTLETY - html entities

### ISSUE THREAD

**Issue by franfranfranfran** [JorgeC05/prj-rev-bwfs-dasmoto#1]
https://github.com/JorgeC05/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found here - https://www.w3schools.com/html/html_entities.asp

**Comment by JorgeC05** [comment]
I have improved the & symbol including in h1 (&amp;), as explained in the documentation
