### ISSUE TITLE
SUBTLETY - heading font size

### ISSUE THREAD

**Issue by franfranfranfran** [JorgeC05/prj-rev-bwfs-dasmoto#2]
https://github.com/JorgeC05/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/means/css/index.css#L33

looks like the actual font-size of the h1 on the page is 200px currently. try targetting the h1 element directly to set the font-size and have it represented correctly. 

more info about why this is happening - many elements on a page are given default values when represented by a browser. heading default values can be found here - https://www.w3schools.com/tags/tag_hn.asp
for h1 elements the default value for font-size is 2em which means 2 times the current font-size. so when you set the font-size to 100px for the div that the h1 is in, it doesn't overwrite the default and then the size of the h1 is 200px. you'll learn more about all this in exercises to come.

**Comment by JorgeC05** [comment]
I read the documentation of  label h(1,2,3,4,5,6) and I decided decrease font-size value to 50px into the <div>
