### ISSUE TITLE
SIMPLIFY - font-family

### ISSUE THREAD

**Issue by franfranfranfran** [JorgeC05/prj-rev-bwfs-dasmoto#3]
https://github.com/JorgeC05/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/means/css/index.css#L15

consider setting font-family just once for the entire page using the universal selector. right now, the p text isn't getting the same font-family as the rest of the page.

**Comment by JorgeC05** [comment]
I performed the changes in the font-family value position and the line was included into universal selector to keep the website structure
