### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [JorgeC05/prj-rev-bwfs-dasmoto#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good start on this project! With a few tweaks the site itself will be looking great. You did an excellent job keeping the project folder and the code neat and organized and good idea to use the divs to help organize the content on the page.

Behind the scenes in the css, there's just a couple areas where you'll need to adjust your styling. Pay extra attention to how the styling you're setting is effecting the elements on the page and be sure that you're targeting the correct elements. 

As a next step try saving your image files locally to your resources folder and then using relative file paths to link to those from your html and css. The link to css on line 6 of your html is a great example and more info can be found here - http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

Keep up the good work!

**Comment by JorgeC05** [comment]
the images was downloaded to start use it with relative routes and take it of local way.
